context:
  version: "0.11.11"

package:
  name: civet
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@danielx/civet/-/civet-${{ version }}.tgz
  sha256: d22df485a73106f46a7782f915e06d7ee9056a86344049f0eec9b08aad5e671e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - civet --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A TypeScript superset that favors more types and less typing
  homepage: https://github.com/DanielXMoore/civet
  repository: https://github.com/DanielXMoore/civet

extra:
  recipe-maintainers:
    - danielnachun
