context:
  version: "0.11.15"

package:
  name: civet
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@danielx/civet/-/civet-${{ version }}.tgz
  sha256: db677aac9677f9fbf6c67b853d96f57a16ccf30d581555a169970ae0ff75bea1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - civet --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A TypeScript superset that favors more types and less typing
  homepage: https://github.com/DanielXMoore/civet
  repository: https://github.com/DanielXMoore/civet

extra:
  recipe-maintainers:
    - danielnachun
