context:
  version: "0.11.13"

package:
  name: civet
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@danielx/civet/-/civet-${{ version }}.tgz
  sha256: 8a2d95c9aac580a660acadfceaa2ffb38a4057cbd6e33c89cb5929d8bb5f751d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - civet --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A TypeScript superset that favors more types and less typing
  homepage: https://github.com/DanielXMoore/civet
  repository: https://github.com/DanielXMoore/civet

extra:
  recipe-maintainers:
    - danielnachun
